- job:
    name: kuryr-libnetwork-fullstack-base
    parent: devstack-tox-functional
    vars: &base_vars
      use_python3: 1
      use_src: 0
      devstack_localrc:
        KURYR_CONFIG_DIR: /etc/kuryr-libnetwork
      tox_envlist: fullstack
      tox_install_siblings: false
      devstack_plugins:
        kuryr-libnetwork: https://opendev.org/openstack/kuryr-libnetwork
        devstack-plugin-container: https://opendev.org/openstack/devstack-plugin-container
    timeout: 7800
    required-projects:
      - opendev.org/openstack/devstack
      - opendev.org/openstack/devstack-plugin-container
      - opendev.org/openstack/kuryr
      - opendev.org/openstack/kuryr-libnetwork
    roles:
      - zuul: opendev.org/openstack/devstack
    irrelevant-files: &base_irrelevant_files
      - ^.*\.rst$
      - ^doc/.*$

- job:
    name: kuryr-libnetwork-rally-base
    parent: rally-task-at-devstack
    timeout: 7800
    vars:
      use_src: 0
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
        kuryr-libnetwork: http://opendev.org/openstack/kuryr-libnetwork
        devstack-plugin-container: https://opendev.org/openstack/devstack-plugin-container
      devstack_localrc:
        USE_PYTHON3: True
      devstack_local_config:
        KURYR_CONFIG_DIR: /etc/kuryr-libnetwork
      rally_task: rally-jobs/kuryr-libnetwork.yaml
    required-projects:
      - opendev.org/openstack/rally-openstack
      - opendev.org/openstack/kuryr
      - opendev.org/openstack/kuryr-libnetwork
      - opendev.org/openstack/devstack-plugin-container
    voting: false

- job:
    name: kuryr-libnetwork-install
    parent: devstack
    timeout: 7800
    required-projects:
      - opendev.org/openstack/devstack
      - opendev.org/openstack/devstack-plugin-container
      - opendev.org/openstack/kuryr
      - opendev.org/openstack/kuryr-libnetwork
    roles:
      - zuul: opendev.org/openstack/devstack
    vars:
      devstack_localrc:
        KURYR_CONFIG_DIR: /etc/kuryr-libnetwork
        KURYR_CAPABILITY_SCOPE: global
      devstack_plugins:
        devstack-plugin-container: https://opendev.org/openstack/devstack-plugin-container
        kuryr-libnetwork: https://opendev.org/openstack/kuryr-libnetwork
    voting: false

- job:
    name: kuryr-libnetwork-fullstack-py3
    parent: kuryr-libnetwork-fullstack-base

- job:
    name: kuryr-libnetwork-fullstack-ipv6-only
    parent: devstack-tempest-ipv6
    irrelevant-files: *base_irrelevant_files
    required-projects:
      - opendev.org/openstack/devstack
      - opendev.org/openstack/devstack-plugin-container
      - opendev.org/openstack/kuryr
      - opendev.org/openstack/kuryr-libnetwork
      - opendev.org/openstack/tempest
    vars:
      <<: *base_vars
      devstack_services:
        s-account: false
        s-object: false
        s-container: false
        s-proxy: false
    run: playbooks/run_fullstack_job.yaml
    post-run: playbooks/post_fullstack_job.yaml

- job:
    name: kuryr-libnetwork-kuryr_lib-src-fullstack
    parent: kuryr-libnetwork-fullstack-base
    vars:
      use_src: 1
    branches: master
    voting: false

- job:
    name: kuryr-libnetwork-rally
    parent: kuryr-libnetwork-rally-base

- job:
    name: kuryr-libnetwork-kuryr_lib-src-rally
    parent: kuryr-libnetwork-rally-base
    vars:
      use_src: 1
    branches: master
    voting: false

- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - kuryr-libnetwork-install
        - kuryr-libnetwork-kuryr_lib-src-fullstack
        - kuryr-libnetwork-kuryr_lib-src-rally
        - kuryr-libnetwork-fullstack-py3
        - kuryr-libnetwork-rally
        - kuryr-libnetwork-fullstack-ipv6-only
    gate:
      jobs:
        - kuryr-libnetwork-kuryr_lib-src-fullstack
        - kuryr-libnetwork-fullstack-py3
        - kuryr-libnetwork-fullstack-ipv6-only
